version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_PATH=users.db
      - SECRET_KEY=your-secret-key-change-in-production
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - postgres-main
    networks:
      - sql-challenges

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - sql-challenges

  postgres-main:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: sql_challenges
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sql-challenges

volumes:
  postgres_data:

networks:
  sql-challenges:
    driver: bridge 