services:
  # Backend API
  - type: web
    name: sql-challenges-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_PATH
        value: /opt/render/project/src/backend/users.db
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /docs

  # Frontend
  - type: web
    name: sql-challenges-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://sql-challenges-backend.onrender.com 